Style fixes

diff --git a/bin/cosy b/bin/cosy
--- a/bin/cosy
+++ b/bin/cosy
@@ -5,7 +5,7 @@ confdir=$HOME/.sysy.d
 tagsfile=$confdir/tags
 tagspath=$(realpath "$scriptpath/../tags")
 
-if which icdiff >/dev/null 2>/dev/null
+if command -v icdiff >/dev/null 2>/dev/null
 then
     nicediff="icdiff"
 else
@@ -21,7 +21,7 @@ find_local_file () {
     while IFS= read -r tag
     do
         local_file=$tagspath/$tag/system$system_file
-        if [ -f "$local_file" ]
+        if [[ -f "$local_file" ]]
         then
             echo "$local_file"
             return
@@ -37,10 +37,7 @@ add_file () {
     sudo -v
     local tag=$1
     local system_file=$2
-    if [ ! -f "$system_file" ]
-    then
-        error "Could not find $system_file"
-    fi
+    [[ -f "$system_file" ]] || error "Could not find $system_file"
     local local_file=$tagspath/$tag/system$system_file
     mkdir -p "$(dirname "$local_file")"
     sudo cat "$system_file" | tee "$local_file"
@@ -50,10 +47,7 @@ sync_file () {
     sudo -v
     local local_file=$1
     local system_file=$2
-    if [ ! -f "$local_file" ]
-    then
-        error "$local_file not handled by cosy"
-    fi
+    [[ -f "$local_file" ]] || error "$local_file not handled by cosy"
     if sudo ls "$system_file" >/dev/null 2>/dev/null
     then
         if ! sudo diff "$system_file" "$local_file" >/dev/null 2>/dev/null
@@ -96,21 +90,15 @@ case "$command" in
     add)
         tag=$1
         system_file=$2
-        if [ ! -f "$system_file" ]
-        then
-            error "Please specify a tag and a system file"
-        fi
+        [[ -f "$system_file" ]] || error "Please specify a tag and a system file"
         add_file "$tag" "$system_file"
         ;;
 
     edit)
         system_file=$1
-        if [ ! -f "$system_file" ]
-        then
-            error "Please specify a system file"
-        fi
+        [[ -f "$system_file" ]] || error "Please specify a system file"
         local_file=$(find_local_file "$system_file")
-        if [ ! -e "$local_file" ]
+        if [[ ! -e "$local_file" ]]
         then
             read -r -p "Tag: " tag < /dev/tty
             add_file "$tag" "$system_file"
@@ -123,7 +111,7 @@ case "$command" in
 
     sync)
         system_file=$1
-        if [ -z "$system_file" ]
+        if [[ -z "$system_file" ]]
         then
             shopt -s globstar nullglob
             while IFS= read -r tag
@@ -131,7 +119,7 @@ case "$command" in
                 filespath=$tagspath/$tag/system
                 for local_file in $filespath/**
                 do
-                    if [ -f "$local_file" ]
+                    if [[ -f "$local_file" ]]
                     then
                         local_file=$(realpath --relative-to "$filespath" "$local_file")
                         system_file=/$local_file
diff --git a/bin/dosy b/bin/dosy
--- a/bin/dosy
+++ b/bin/dosy
@@ -28,7 +28,7 @@ find_local_file_tag () {
     while IFS= read -r tag
     do
         this_local_file=$tagspath/$tag/dotfiles/$local_file
-        if [ -e "$this_local_file" ]
+        if [[ -e "$this_local_file" ]]
         then
             echo "$tag"
             return
@@ -39,25 +39,15 @@ find_local_file_tag () {
 sync_file () {
     local local_file=$1
     local file=$2
-    if [ ! -e "$local_file" ]
+    [[ -e "$local_file" ]] || error "$local_file not found"
+    if [[ -d "$local_file" && -e "$local_file/.sub" ]]
     then
-        error "$local_file not found"
-    fi
-    if [ -d "$local_file" ] && [ -e "$local_file/.sub" ]
-    then
-        if [ -L "$file" ]
-        then
-            error "$file is a link"
-        fi
-        if [ -f "$file" ]
-        then
-            error "$file is a file, but expected a directory"
-        fi
+        [[ ! -L "$file" ]] || error "$file is a link"
         mkdir -p "$file"
         for f in $local_file/*
         do
             base=$(basename "$f")
-            if [ "$base" != ".sub" ]
+            if [[ "$base" != ".sub" ]]
             then
                 sync_file "$f" "$file/$base"
             fi
@@ -74,29 +64,17 @@ case "$command" in
     add)
         tag=$1
         file=$2
-        if [ ! -e "$file" ]
-        then
-            error "Please specify a tag and a file or directory"
-        fi
-        if [ -L "$file" ]
-        then
-            error "$file is a symlink"
-        fi
+        [[ -e "$file" ]] || error "Please specify a tag and a file or directory"
+        [[ ! -L "$file" ]] || error "$file is a symlink"
         custom_file=$3
-        if [ -z "$custom_file" ]
+        if [[ -z "$custom_file" ]]
         then
             file=$(realpath --relative-to "$HOME" "$file")
-            if [ "$(dirname "$file")" != "." ] || [ "${file:0:1}" != "." ] || [ "$file" == "." ]
-            then
-                error "$file is not a dotfile"
-            fi
+            [[ "$(dirname "$file")" == "." && "${file:0:1}" == "." && "$file" != "." ]] || error "$file is not a dotfile"
             undotted_file=${file:1}
             dotfilespath=$tagspath/$tag/dotfiles
             local_file=$dotfilespath/$undotted_file
-            if [ -f "$local_file" ]
-            then
-                error "$file is already handled by dosy with tag $tag"
-            fi
+            [[ ! -f "$local_file" ]] || error "$file is already handled by dosy with tag $tag"
             mkdir -p "$dotfilespath"
             mv "$HOME/$file" "$local_file"
             ln -s "$(realpath "$local_file")" "$HOME/$file"
@@ -111,7 +89,7 @@ case "$command" in
             filespath=$tagspath/$tag/dotfiles
             for local_file in $filespath/*
             do
-                if [ -e "$local_file" ]
+                if [[ -e "$local_file" ]]
                 then
                     local_file=$(realpath --relative-to "$filespath" "$local_file")
                     file=$HOME/.$local_file
@@ -120,22 +98,16 @@ case "$command" in
                 fi
             done
             custompath=$tagspath/$tag/custom
-            if [ -f "$custompath" ]
+            if [[ -f "$custompath" ]]
             then
                 filespath=$tagspath/$tag/files
                 while IFS= read -r line
                 do
                     readarray -d ';' -t args <<< "$line;"
-                    if [ "${#args[@]}" -lt 3 ]
-                    then
-                        error "Corrupt line in $custompath"
-                    fi
+                    [[ "${#args[@]}" -eq 3 ]] || error "Corrupt line in $custompath"
                     custom_file=${args[0]}
                     file=${args[1]}
-                    if [ "${file:0:1}" != "/" ]
-                    then
-                        file=$HOME/$file
-                    fi
+                    [[ "${file:0:1}" == "/" ]] || file=$HOME/$file
                     sync_file "$filespath/$custom_file" "$file"
                 done < "$custompath"
             fi
@@ -144,24 +116,14 @@ case "$command" in
 
     unhandle)
         file=$1
-        if [ ! -e "$file" ]
-        then
-            error "Please specify a file or directory"
-        fi
+        [[ -e "$file" ]] || error "Please specify a file or directory"
         local_file=$(realpath --no-symlinks --relative-to "$HOME" "$file")
-        if [ "$(dirname "$local_file")" != "." ] || [ "${local_file:0:1}" != "." ] || [ "$local_file" == "." ]
-        then
-            error "$local_file is not a dotfile or not handled by dosy"
-        fi
+        [[ "$(dirname "$local_file")" == "." && "${local_file:0:1}" == "." && "$local_file" != "." ]] ||  error "$local_file is not a dotfile or not handled by dosy"
         undotted_file=${local_file:1}
         tag=$(find_local_file_tag "$undotted_file")
-        if [ ! -z "$tag" ]
-        then
-            local_file=$tagspath/$tag/dotfiles/$undotted_file
-        else
-            error "$local_file not handled by dosy as a dotfile"
-        fi
-        if [ "$(realpath "$file")" != "$local_file" ]
+        [[ -n "$tag" ]] ||  error "$local_file not handled by dosy as a dotfile"
+        local_file=$tagspath/$tag/dotfiles/$undotted_file
+        if [[ "$(realpath "$file")" != "$local_file" ]]
         then
             info "$file not currently synced"
             if ask_user "Delete handle anyway?" "n"
diff --git a/bin/pasy b/bin/pasy
--- a/bin/pasy
+++ b/bin/pasy
@@ -20,10 +20,7 @@ call_module () {
 check_module () {
     local module=$1
     local modulefile=$modulespath/$module
-    if [ ! -f "$modulefile" ]
-    then
-        error "Module $module not found"
-    fi
+    [[ -f "$modulefile" ]] || error "Module $module not found"
 }
 
 get_packages () {
@@ -31,7 +28,7 @@ get_packages () {
     while IFS= read -r tag
     do
         packagesfile=$tagspath/$tag/packages/$module
-        if [ -f "$packagesfile" ]
+        if [[ -f "$packagesfile" ]]
         then
             grep -v -e "^#" < "$packagesfile" | cut -f1 -d' ' # | tr '\n' ' '
         fi
@@ -44,9 +41,9 @@ call_module_for_all_packages () {
     local desc=$3
     readarray -t packages <<< "$(get_packages "$module")"
     packages_count=${#packages[@]}
-    if [ "$packages_count" -gt 0 ] && [ ! -z "${packages[0]}" ]
+    if [[ "$packages_count" -gt 0 && -n "${packages[0]}" ]]
     then
-        if [ ! -z "$desc" ]
+        if [[ -n "$desc" ]]
         then
             info "$desc $module ($packages_count selected)..."
         fi
@@ -60,7 +57,7 @@ case "$command" in
 
     bootstrap)
         module=$1
-        if [ -z "$module" ]
+        if [[ -z "$module" ]]
         then
             for module in $modulespath/*
             do
@@ -75,16 +72,16 @@ case "$command" in
 
     diff)
         module=$1
-        [ ! -z "$module" ] || error "Please specify a module"
+        [[ -n "$module" ]] || error "Please specify a module"
         check_module "$module"
         call_module_for_all_packages "$module" diff
         ;;
 
     edit)
         module=$1
-        [ ! -z "$module" ] || error "Please specify a module"
+        [[ -n "$module" ]] || error "Please specify a module"
         tag=$2
-        [ ! -z "$tag" ] || error "Please specify a tag"
+        [[ -n "$tag" ]] || error "Please specify a tag"
         check_module "$module"
         packages_file=$tagspath/$tag/packages/$module
         open_in_editor "$packages_file"
@@ -92,14 +89,11 @@ case "$command" in
 
     install)
         module=$1
-        [ ! -z "$module" ] || error "Please specify a module"
+        [[ -n "$module" ]] || error "Please specify a module"
         tag=$2
-        [ ! -z "$tag" ] || error "Please specify a tag"
+        [[ -n "$tag" ]] || error "Please specify a tag"
         shift 2
-        if [ -z "$1" ]
-        then
-            error "Please specify at least one package to install"
-        fi
+        [[ -n "$1" ]] || error "Please specify at least one package to install"
         check_module "$module"
         packagespath=$tagspath/$tag/packages
         packagesfile=$packagespath/$module
@@ -119,7 +113,7 @@ case "$command" in
 
     sync)
         module=$1
-        if [ -z "$module" ]
+        if [[ -z "$module" ]]
         then
             for module in $modulespath/*
             do
@@ -133,18 +127,17 @@ case "$command" in
         ;;
 
     uninstall)
-        module=${1:?"Please specify a module"}
-        tag=${2:?"Please specify a tag"}
+        module=$1
+        [[ -n "$module" ]] || error "Please specify a module"
+        tag=$2
+        [[ -n "$tag" ]] || error "Please specify a tag"
         shift 2
-        if [ -z "$1" ]
-        then
-            error "Please specify at least one package to install"
-        fi
+        [[ -n "$1" ]] || error "Please specify at least one package to uninstall"
         check_module "$module"
         call_module "$module" uninstall "$@"
         packagespath=$tagspath/$tag/packages
         packagesfile=$packagespath/$module
-        if [ -f "$packagesfile" ]
+        if [[ -f "$packagesfile" ]]
         then
             packages_str=$(cat "$packagesfile")
             for p in "$@"
@@ -157,7 +150,7 @@ case "$command" in
 
     update)
         module=$1
-        if [ -z "$module" ]
+        if [[ -z "$module" ]]
         then
             for module in $modulespath/*
             do
