Various fixes and cleanup

diff --git a/bin/cosy b/bin/cosy
--- a/bin/cosy
+++ b/bin/cosy
@@ -39,8 +39,7 @@ add_file () {
     local system_file=$2
     if [ ! -f "$system_file" ]
     then
-        echo "Could not find $system_file" 1>&2
-        exit 1
+        error "Could not find $system_file"
     fi
     local local_file=$tagspath/$tag/system$system_file
     mkdir -p "$(dirname "$local_file")"
@@ -53,8 +52,7 @@ sync_file () {
     local system_file=$2
     if [ ! -f "$local_file" ]
     then
-        echo "$local_file not handled by cosy" 1>&2
-        exit 1
+        error "$local_file not handled by cosy"
     fi
     if sudo ls "$system_file" >/dev/null 2>/dev/null
     then
@@ -65,16 +63,16 @@ sync_file () {
             then
                 sudo cat "$local_file" | sudo tee "$system_file" >/dev/null
             else
-                echo "Skipped $system_file"
+                info "Skipped $system_file"
             fi
         fi
     else
         if is_text_file "$local_file"
         then
-            echo "New $system_file:"
+            info "New $system_file:"
             less -X -F "$local_file"
         else
-            echo "New $system_file (binary)"
+            info "New $system_file (binary)"
         fi
         if ask_user "Add file to system?" "y"
         then
@@ -86,13 +84,13 @@ sync_file () {
                 sudo chmod og+rX "$system_file"
             fi
         else
-            echo "Skipped $system_file"
+            info "Skipped $system_file"
         fi
     fi
 }
 
 command=$1
-shift
+shift || true
 case "$command" in
 
     add)
@@ -100,8 +98,7 @@ case "$command" in
         system_file=$2
         if [ ! -f "$system_file" ]
         then
-            echo "Please specify a tag and a system file" 1>&2
-            exit 2
+            error "Please specify a tag and a system file"
         fi
         add_file "$tag" "$system_file"
         ;;
@@ -110,8 +107,7 @@ case "$command" in
         system_file=$1
         if [ ! -f "$system_file" ]
         then
-            echo "Please specify a system file" 1>&2
-            exit 2
+            error "Please specify a system file"
         fi
         local_file=$(find_local_file "$system_file")
         if [ ! -e "$local_file" ]
diff --git a/bin/dosy b/bin/dosy
--- a/bin/dosy
+++ b/bin/dosy
@@ -42,17 +42,13 @@ sync_file () {
     local file=$2
     if [ ! -e "$local_file" ]
     then
-        echo "$local_file not found" 1>&2
-        exit 2
+        error "$local_file not found"
     fi
-    if [ ! -e "$file" ] || [ "$(realpath "$file")" != "$local_file" ]
-    then
-        ln -si "$local_file" "$file"
-    fi
+    ensure_link "$local_file" "$file"
 }
 
 command=$1
-shift
+shift || true
 case "$command" in
 
     add)
@@ -60,8 +56,7 @@ case "$command" in
         file=$2
         if [ ! -e "$file" ]
         then
-            echo "Please specify a tag and a file or directory" 1>&2
-            exit 2
+            error "Please specify a tag and a file or directory"
         fi
         custom_file=$3
         if [ -z "$custom_file" ]
@@ -69,16 +64,14 @@ case "$command" in
             file=$(realpath --relative-to "$HOME" "$file")
             if [ "$(dirname "$file")" != "." ] || [ "${file:0:1}" != "." ] || [ "$file" == "." ]
             then
-                echo "This is not a dotfile" 1>&2
-                exit 2
+                error "This is not a dotfile"
             fi
             undotted_file=${file:1}
             dotfilespath=$tagspath/$tag/dotfiles
             local_file=$dotfilespath/$undotted_file
             if [ -f "$local_file" ]
             then
-                echo "$file is already handled by dosy with tag $tag" 1>&2
-                exit 2
+                error "$file is already handled by dosy with tag $tag"
             fi
             mkdir -p "$dotfilespath"
             mv "$HOME/$file" "$local_file"
@@ -118,8 +111,7 @@ case "$command" in
         file=$1
         if [ ! -e "$file" ]
         then
-            echo "Please specify a file or directory" 1>&2
-            exit 2
+            error "Please specify a file or directory"
         fi
         local_file=$(realpath --relative-to "$HOME" "$file")
         tag=$(find_local_file_tag "$local_file" "files")
@@ -132,13 +124,12 @@ case "$command" in
             then
                 local_file=$tagspath/$tag/dotfiles/$local_file
             else
-                echo "$file not handled by dosy" 1>&2
-                exit 2
+                error "$file not handled by dosy"
             fi
         fi
         if [ "$(realpath "$file")" != "$local_file" ]
         then
-            echo "$file not currently synced" 1>&2
+            info "$file not currently synced"
             if ask_user "Delete handle anyway?" "n"
             then
                 rm -rfi "$local_file"
diff --git a/bin/pasy b/bin/pasy
--- a/bin/pasy
+++ b/bin/pasy
@@ -22,8 +22,7 @@ check_module () {
     local modulefile=$modulespath/$module
     if [ ! -f "$modulefile" ]
     then
-        echo "Module $module not found" 1>&2
-        exit 2
+        error "Module $module not found"
     fi
 }
 
@@ -34,13 +33,29 @@ get_packages () {
         packagesfile=$tagspath/$tag/packages/$module
         if [ -f "$packagesfile" ]
         then
-            grep -v -e "^#" < "$packagesfile" | cut -f1 -d' '
+            grep -v -e "^#" < "$packagesfile" | cut -f1 -d' ' # | tr '\n' ' '
         fi
     done < "$tagsfile"
 }
 
+call_module_for_all_packages () {
+    local module=$1
+    local command=$2
+    local desc=$3
+    readarray -t packages <<< "$(get_packages "$module")"
+    packages_count=${#packages[@]}
+    if [ "$packages_count" -gt 0 ] && [ ! -z "${packages[0]}" ]
+    then
+        if [ ! -z "$desc" ]
+        then
+            info "$desc $module ($packages_count selected)..."
+        fi
+        call_module "$module" "$command" "${packages[@]}"
+    fi
+}
+
 command=$1
-shift
+shift || true
 case "$command" in
 
     bootstrap)
@@ -50,61 +65,55 @@ case "$command" in
             for module in $modulespath/*
             do
                 module=$(basename "$module")
-                packages=$(get_packages "$module")
-                if [ ! -z "$packages" ]
-                then
-                    echo "Bootstrapping $module ($(wc -l "$packages") selected..."
-                    call_module "$module" bootstrap
-                fi
+                call_module_for_all_packages "$module" bootstrap Bootstrapping
             done
         else
             check_module "$module"
-            call_module "$module" bootstrap
+            call_module_for_all_packages "$module" bootstrap Bootstrapping
         fi
         ;;
 
     diff)
-        module=${1:?"Please specify a module"}
+        module=$1
+        [ ! -z "$module" ] || error "Please specify a module"
         check_module "$module"
-        packages=$(get_packages "$module")
-        if [ ! -z "$packages" ]
-        then
-            call_module "$module" diff "$packages"
-        fi
+        call_module_for_all_packages "$module" diff
         ;;
 
     edit)
-        module=${1:?"Please specify a module"}
-        tag=${2:?"Please specify a tag"}
+        module=$1
+        [ ! -z "$module" ] || error "Please specify a module"
+        tag=$2
+        [ ! -z "$tag" ] || error "Please specify a tag"
         check_module "$module"
         packages_file=$tagspath/$tag/packages/$module
         open_in_editor "$packages_file"
         ;;
 
     install)
-        module=${1:?"Please specify a module"}
-        shift
-        tag=${1:?"Please specify a tag"}
-        shift
+        module=$1
+        [ ! -z "$module" ] || error "Please specify a module"
+        tag=$2
+        [ ! -z "$tag" ] || error "Please specify a tag"
+        shift 2
         if [ -z "$1" ]
         then
-            echo "Please specify at least one package to install" 1>&2
-            exit 2
+            error "Please specify at least one package to install"
         fi
         check_module "$module"
         packagespath=$tagspath/$tag/packages
         packagesfile=$packagespath/$module
         mkdir -p "$packagespath"
         touch "$packagesfile"
-        packages=$(cat "$packagesfile")
+        packages_str=$(cat "$packagesfile")
         if call_module "$module" install "$@"
         then
             for p in "$@"
             do
                 desc=$(call_module "$module" desc "$p")
-                packages=$(echo -e "$packages\\n$p # $desc" | sort | uniq)
+                packages_str=$(echo -e "$packages_str\\n$p # $desc" | sort | uniq)
             done
-            echo "$packages" > "$packagesfile"
+            echo "$packages_str" > "$packagesfile"
         fi
         ;;
 
@@ -115,32 +124,21 @@ case "$command" in
             for module in $modulespath/*
             do
                 module=$(basename "$module")
-                packages=$(get_packages "$module")
-                if [ ! -z "$packages" ]
-                then
-                    echo "Syncing $module ($(wc -l "$packages") selected..."
-                    call_module "$module" sync "$packages"
-                fi
+                call_module_for_all_packages "$module" sync Syncing
             done
         else
             check_module "$module"
-            packages=$(get_packages "$module")
-            if [ ! -z "$packages" ]
-            then
-                call_module "$module" sync "$packages"
-            fi
+            call_module_for_all_packages "$module" sync Syncing
         fi
         ;;
 
     uninstall)
         module=${1:?"Please specify a module"}
-        shift
-        tag=${1:?"Please specify a tag"}
-        shift
+        tag=${2:?"Please specify a tag"}
+        shift 2
         if [ -z "$1" ]
         then
-            echo "Please specify at least one package to install" 1>&2
-            exit 2
+            error "Please specify at least one package to install"
         fi
         check_module "$module"
         call_module "$module" uninstall "$@"
@@ -148,12 +146,12 @@ case "$command" in
         packagesfile=$packagespath/$module
         if [ -f "$packagesfile" ]
         then
-            packages=$(cat "$packagesfile")
+            packages_str=$(cat "$packagesfile")
             for p in "$@"
             do
-                packages=$(echo "$packages" | grep -v -e "^$p #")
+                packages_str=$(echo "$packages_str" | grep -v -e "^$p #")
             done
-            echo "$packages" > "$packagesfile"
+            echo "$packages_str" > "$packagesfile"
         fi
         ;;
 
@@ -164,20 +162,11 @@ case "$command" in
             for module in $modulespath/*
             do
                 module=$(basename "$module")
-                packages=$(get_packages "$module")
-                if [ ! -z "$packages" ]
-                then
-                    echo "Updating $module ($(wc -l "$packages") selected..."
-                    call_module "$module" update "$packages"
-                fi
+                call_module_for_all_packages "$module" update Updating
             done
         else
             check_module "$module"
-            packages=$(get_packages "$module")
-            if [ ! -z "$packages" ]
-            then
-                call_module "$module" update "$packages"
-            fi
+            call_module_for_all_packages "$module" update Updating
         fi
         ;;
 
